### ISSUE TITLE
initialized but not working

### ISSUE THREAD

**Issue by remotelink** [tau-OS/dash-to-dock#1]
### What Happened?

hi,
thank you for adopting "dash to dock" to v42 of gnome. my system is a debian/sid.

### Steps to Reproduce

to the extension necessary installed packages:

```
$ dpkg -l | grep -E "gnome-shell|sassc" 
ii  chrome-gnome-shell                       10.1-5                             all          GNOME Shell extensions integration for web browsers
ii  gnome-shell                              42.0-2                             amd64        graphical shell for the GNOME desktop
ii  gnome-shell-common                       42.0-2                             all          common files for the GNOME graphical shell
ii  gnome-shell-extension-prefs              42.0-2                             amd64        tool to enable / disable GNOME Shell extensions
ii  gnome-shell-extensions                   42.0-2                             all          Extensions to extend functionality of GNOME Shell
ii  sassc                                    3.6.1+20201027-2                   amd64        C/C++ port of the Sass CSS precompiler - command-line tool

```

after 'make install' we see:

```
$ gnome-extensions list
dash-to-dock@tauos.co
apps-menu@gnome-shell-extensions.gcampax.github.com
...

```
and after a restart of GDM3:

```
$ gnome-extensions info dash-to-dock@tauos.co 
dash-to-dock@tauos.co
  Name: Dash to Dock
  Description: A dock for the Gnome Shell. A modified version of the Dash to Dock extension for tauOS
  Path: /home/x/.local/share/gnome-shell/extensions/dash-to-dock@tauos.co
  URL: https://micheleg.github.io/dash-to-dock/
  Original author: micxgx@gmail.com
  Version: 71
  State: INITIALIZED
```

so it should work ... but we can not enable the "settings". the dotted icon in the dock is the same as in original gnome.

### Expected Behavior

the dotted icon in gnome dash should enable "settings of dash-to-dock" while clicking right.
what did i miss?

tnx remotelink  

### OS Version

Other Linux

### Software Version

Latest release (I have run all updates)

### Log Output

```shell
no logs ...
```

### Hardware Info

not relevant

**Comment by remotelink** [comment]
sorry, i was not familiar with gnome-extensions. meanwhile a solution for activating this extension is:

set your preferences:
`$ gnome-extensions prefs dash-to-dock@tauos.co`  
enable extension:
`$ gnome-extensions enable dash-to-dock@tauos.co`

... this is working on gnome-shell version: 42 (i love to find my dock on the left side of screen).

**Comment by nothingneko** [comment]
Hey, if everything is resolved I’ll close the issue. Let us know if you need more help!
